name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "main" ]
  pull_request:


permissions:
  contents : read
  id-token : 'write'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout source code
        uses: actions/checkout@v4

      #- id: auth
        #uses: google-github-actions/auth@v2.0.0
        #with:
          #workload_identity_provider: 'projects/project-id/locations/global/WorkloadIdentityPools/nameofthepool/providers/github'
          #service_account: 'poolname@projectname.iam.gserviceaccount.com'

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Create image tag from short SHA
      - name: Set image tags
        id: vars
        run: echo "TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      # Step 4: Build and push Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/testimage:latest
            ${{ secrets.DOCKER_USERNAME }}/testimage:${{ steps.vars.outputs.TAG }}
